name: Node.js CI

on:
  push:
    branches:
      - main    # Trigger on push to the main branch
  pull_request:
    branches:
      - main    # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: self-hosted  # Using the self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This ensures that the code is checked out

    - name: Install Node.js (Dynamic installation)
      run: |
        # Install Node.js (if not pre-installed)
        sudo apt-get update
        sudo apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs

        # Verify Node.js installation
        node -v
        npm -v

    - name: Install dependencies
      run: |
        cd app   # Change directory to where package.json is located
        sudo apt install npm
        
        npm install  # Install dependencies from package.json
