
name: Node.js CI
# install all softwares on ec2 manucally 
on:
  push:
    branches:
      - main    # Trigger on push to the main branch
  pull_request:
    branches:
      - main    # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: self-hosted  # Using the self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This ensures that the code is checked out

    - name: Install Node.js (Dynamic installation)
      run: |
        # Install Node.js (if not pre-installed)
        sudo apt-get update
        sudo apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
<<<<<<< HEAD
        # Verify Node.js installation
        node -v
=======

        # Verify Node.js installation
        node -v
        npm -v
>>>>>>> 99ee2d0ff171063c03fd9a198639794745e59aeb

    - name: Install dependencies
      run: |
        sudo apt install npm
<<<<<<< HEAD
=======

>>>>>>> 99ee2d0ff171063c03fd9a198639794745e59aeb
