name: Node.js CI

on:
  push:
    branches:
      - main    # Or any other branch you want to trigger on
  pull_request:
    branches:
      - main    # Or any other branch you want to trigger on

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js (Dynamic installation)
      run: |
        # Update and install required dependencies
        sudo apt-get update
        sudo apt-get install -y curl

        # Install Node.js (you can specify a version, here I'm using version 16)
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install dependencies
      run: npm install
