name: Node.js CI

on:
  push:
    branches:
      - main    # Or any other branch you want to trigger on
  pull_request:
    branches:
      - main    # Or any other branch you want to trigger on

jobs:
  build:
    runs-on: self-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm rub build

